### ISSUE TITLE
readthedocs not up-to-date

### ISSUE THREAD

**Issue by doegox** [newaetech/ChipSHOUTER-python#7]
Hi

I'm not sure why https://chipshouter.readthedocs.io/en/latest/ is not reflecting automatically latest master, but e.g. the very first example still mentions "cs.arm = 1" while master doc is fixed : https://github.com/newaetech/ChipSHOUTER-python/blob/master/chipshouter/chipshouter.py#L58

**Comment by colinoflynn** [comment]
I think you fixed this now... RTD error log showed:

```
 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyserial==3.4
  Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
ERROR: Could not find a version that satisfies the requirement PyCRC==1.21 (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for PyCRC==1.21 (from -r requirements.txt (line 2))
```

With your other PR merged in we're back in business. I hadn't setup a notice when the builds started to fail so I never noticed.
